version: '2.1'

services:

  bash:
    image: smartweb/php:7.1-cli-dev
    entrypoint: 'bash'
    working_dir: '/var/www/html'
    volumes:
      - .:/var/www/html
    networks:
      - nats-test
    environment:
      XDEBUG_CONFIG: idekey=PHPSTORM remote_host=192.168.1.167 remote_enable=1
      PHP_IDE_CONFIG: serverName=docker

  nats-streaming:
    image: nats-streaming
    command: "-p 4223 -m 8223"
    networks:
      - nats-test

networks:
    nats-test:
